/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zulf
 */
public class Play3 extends javax.swing.JFrame {

    public int nilai3 = Play.nilainya;
    String nilai3tru = "" + nilai3;

    public Play3() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.score.setText(nilai3tru);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        soal = new javax.swing.JLabel();
        stan = new javax.swing.JButton();
        choirul = new javax.swing.JButton();
        zul = new javax.swing.JButton();
        sopyan = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        scoreguide = new javax.swing.JLabel();
        Clue = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("LetterOMatic!", 0, 24)); // NOI18N
        title.setText("Soal 3");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        soal.setFont(new java.awt.Font("LetterOMatic!", 0, 14)); // NOI18N
        soal.setText("<html> Siapakah Asdos Paling kece ? Clue: Lihat Foto </html>");
        soal.setToolTipText("");
        soal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(soal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 90));

        stan.setText("STAN");
        stan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stanActionPerformed(evt);
            }
        });
        getContentPane().add(stan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, 50));

        choirul.setText("CHOIRUL");
        choirul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choirulActionPerformed(evt);
            }
        });
        getContentPane().add(choirul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 110, 50));

        zul.setText("ZUL");
        zul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zulActionPerformed(evt);
            }
        });
        getContentPane().add(zul, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 50));

        sopyan.setText("SOPYAN");
        sopyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sopyanActionPerformed(evt);
            }
        });
        getContentPane().add(sopyan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 50));

        score.setFont(new java.awt.Font("LetterOMatic!", 0, 18)); // NOI18N
        score.setText("0");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        scoreguide.setFont(new java.awt.Font("LetterOMatic!", 0, 18)); // NOI18N
        scoreguide.setText("SCORE :");
        getContentPane().add(scoreguide, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        Clue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buatinterface/satans.png"))); // NOI18N
        getContentPane().add(Clue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buatinterface/bagi2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stanActionPerformed
        new Final().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stanActionPerformed

    private void choirulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choirulActionPerformed
        new Final().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_choirulActionPerformed

    private void zulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zulActionPerformed
        Play.nilainya++;
        score.setText("" + Play.nilainya);
        new Final().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_zulActionPerformed

    private void sopyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sopyanActionPerformed
        new Final().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sopyanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clue;
    private javax.swing.JLabel background;
    private javax.swing.JButton choirul;
    private javax.swing.JLabel score;
    private javax.swing.JLabel scoreguide;
    private javax.swing.JLabel soal;
    private javax.swing.JButton sopyan;
    private javax.swing.JButton stan;
    private javax.swing.JLabel title;
    private javax.swing.JButton zul;
    // End of variables declaration//GEN-END:variables
}
