/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zulf
 */
public class Play extends javax.swing.JFrame {

    public static int nilainya = 0;

    public Play() {
        initComponents();
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        soal = new javax.swing.JLabel();
        suharto = new javax.swing.JButton();
        sukurin = new javax.swing.JButton();
        sukarno = new javax.swing.JButton();
        sumanto = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        scoreguide = new javax.swing.JLabel();
        Clue = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        test = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("LetterOMatic!", 0, 24)); // NOI18N
        title.setText("Soal 1");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        soal.setFont(new java.awt.Font("LetterOMatic!", 0, 14)); // NOI18N
        soal.setText("<html> Siapakah Presiden Pertama Indonesia ? Clue: Lihat Foto </html>");
        soal.setToolTipText("");
        getContentPane().add(soal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 70));

        suharto.setText("SOEHARTO");
        suharto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhartoActionPerformed(evt);
            }
        });
        getContentPane().add(suharto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 110, 50));

        sukurin.setText("SOEKOREN");
        sukurin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukurinActionPerformed(evt);
            }
        });
        getContentPane().add(sukurin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 110, 50));

        sukarno.setText("SOEKARNO");
        sukarno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukarnoActionPerformed(evt);
            }
        });
        getContentPane().add(sukarno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 50));

        sumanto.setText("SOEMANTO");
        sumanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumantoActionPerformed(evt);
            }
        });
        getContentPane().add(sumanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 50));

        score.setFont(new java.awt.Font("LetterOMatic!", 0, 18)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("0");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        scoreguide.setFont(new java.awt.Font("LetterOMatic!", 0, 18)); // NOI18N
        scoreguide.setForeground(new java.awt.Color(255, 255, 255));
        scoreguide.setText("SCORE :");
        getContentPane().add(scoreguide, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        Clue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buatinterface/kartolo.png"))); // NOI18N
        getContentPane().add(Clue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buatinterface/bagi2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        test.setText("hit me");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suhartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhartoActionPerformed
        new Play2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suhartoActionPerformed

    private void sukurinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukurinActionPerformed
        new Play2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sukurinActionPerformed

    private void sukarnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukarnoActionPerformed
        nilainya++;
        score.setText("" + nilainya);
        new Play2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sukarnoActionPerformed

    private void sumantoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumantoActionPerformed
        new Play2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sumantoActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        nilainya++;
        score.setText("" + nilainya);


    }//GEN-LAST:event_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clue;
    private javax.swing.JLabel background;
    private javax.swing.JLabel score;
    private javax.swing.JLabel scoreguide;
    private javax.swing.JLabel soal;
    private javax.swing.JButton suharto;
    private javax.swing.JButton sukarno;
    private javax.swing.JButton sukurin;
    private javax.swing.JButton sumanto;
    private javax.swing.JButton test;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
